services:

  nginx:
    build:
      context: ./nginx

    container_name: terrifyingtees-nginx

    ports:
      - "80:80"

    depends_on:
      - frontend
      - backend
    
    restart: unless-stopped

  backend:
    build:
      context: ./backend

    container_name: terrifyingtees-backend

    env_file:
      - ./backend/.env

    expose:
      - "3001"
    
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend

    container_name: terrifyingtees-frontend

    expose:
      - "3000"

    depends_on:
      - backend
    
    restart: unless-stopped
