name: CI

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  docker-build:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Build Backend Image
        run: |
          docker build -t backend ./backend

      - name: Build Frontend Image
        run: |
          docker build -t frontend ./frontend